export interface Product {
  id: number;
  name: string;
  slug: string;
  category: string;
  subcategory?: string;
  price: number;
  originalPrice?: number;
  description: string;
  fullDescription?: string;
  image: string;
  images?: string[];
  popularity: number;
  inStock: boolean;
  isPopular?: boolean;
  nutritionalInfo?: {
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
    calcium?: number;
  };
  ingredients?: string[];
  weight?: string;
  servings?: number;
  storageInstructions?: string;
  brand?: string;
}

export const categories = [
  { name: 'Instant Porridge', slug: 'instant-porridge', count: 6, icon: '/categories/porrige.png' },
  { name: 'Herbals Tea Bag', slug: 'herbals-tea-bag', count: 13, icon: '/categories/tea-bag.png' },
  { name: 'Roots & Yums', slug: 'roots-yums', count: 0, icon: '/categories/roots.png' },
  { name: 'Fruits Powder & Chips', slug: 'fruits-powder-chips', count: 6, icon: '/categories/chips.png' },
  { name: 'Instant Curry', slug: 'instant-curry', count: 4, icon: '/categories/curry.png' },
  { name: 'Pepo', slug: 'pepo', count: 6, icon: '/categories/porrige.png' },
];

export const products: Product[] = [
  // ========== Instant Porridge ==========
  {
    id: 1,
    name: 'Welpenala Porridge',
    slug: 'welpenala-porridge',
    category: 'Instant Porridge',
    price: 190,
    description: 'Nutritious instant porridge made from Welpenala leaves',
    fullDescription: 'Welpenala (Trianthema portulacastrum) is a traditional leafy vegetable known for its cooling properties and high mineral content. This instant porridge combines the goodness of Welpenala with fine rice flour for a quick, healthy meal. Perfect for breakfast or a light dinner, it supports digestion and provides essential nutrients.',
    image: '/products/porridge/welpenela.jpeg',
    popularity: 82,
    inStock: true,
    nutritionalInfo: { calories: 210, protein: 5.2, carbs: 38, fat: 3.5, calcium: 120 },
    ingredients: ['Rice Flour', 'Welpenala Leaf Powder', 'Coconut Milk Powder', 'Salt'],
    weight: '50g (makes 2 servings)',
    servings: 2,
  },
  {
    id: 2,
    name: 'Polpala Porridge',
    slug: 'polpala-porridge',
    category: 'Instant Porridge',
    price: 190,
    description: 'Wholesome porridge with Polpala (Aerva lanata)',
    fullDescription: 'Polpala is a revered medicinal herb in Sri Lankan tradition, used to support kidney health and urinary wellness. Our instant Polpala porridge blends this herb with creamy rice and coconut for a nourishing, easy-to-prepare meal. Enjoy the earthy flavor and health benefits in minutes.',
    image: '/products/porridge/polpala.jpeg',
    popularity: 88,
    inStock: true,
    isPopular: true,
    nutritionalInfo: { calories: 205, protein: 4.8, carbs: 37, fat: 3.8, calcium: 95 },
    ingredients: ['Rice Flour', 'Polpala Leaf Powder', 'Coconut Milk Powder', 'Salt'],
    weight: '50g',
    servings: 2,
  },
  {
    id: 3,
    name: 'Hinbovitiya Porridge',
    slug: 'hinbovitiya-porridge',
    category: 'Instant Porridge',
    price: 195,
    description: 'Traditional porridge with Hinbovitiya (Enicostema axillare)',
    fullDescription: 'Hinbovitiya is a bitter herb widely used in Ayurveda for blood purification and diabetes management. Our instant porridge balances the bitterness with coconut and rice, creating a unique, health-focused meal. Regular consumption may help regulate blood sugar and improve metabolism.',
    image: '/products/porridge/bovitiya.jpeg',
    popularity: 75,
    inStock: true,
    nutritionalInfo: { calories: 200, protein: 4.5, carbs: 36, fat: 3.6 },
    ingredients: ['Rice Flour', 'Hinbovitiya Leaf Powder', 'Coconut Milk Powder', 'Salt'],
    weight: '50g',
    servings: 2,
  },
  {
    id: 4,
    name: 'Curry Leaves Porridge',
    slug: 'curry-leaves-porridge',
    category: 'Instant Porridge',
    price: 185,
    description: 'Aromatic porridge infused with fresh curry leaves',
    fullDescription: 'Curry leaves are not just for tempering – they are packed with iron, calcium, and antioxidants. This instant porridge brings the distinct aroma and health benefits of curry leaves into a warm, comforting bowl. Great for hair health, digestion, and overall wellness.',
    image: '/products/porridge/karapincha.jpeg',
    popularity: 85,
    inStock: true,
    nutritionalInfo: { calories: 195, protein: 5.0, carbs: 35, fat: 3.2, calcium: 180 },
    ingredients: ['Rice Flour', 'Curry Leaf Powder', 'Coconut Milk Powder', 'Salt'],
    weight: '50g',
    servings: 2,
  },
  {
    id: 5,
    name: 'Katupila Porridge',
    slug: 'katupila-porridge',
    category: 'Instant Porridge',
    price: 200,
    description: 'Detoxifying porridge with Katupila (Scoparia dulcis)',
    fullDescription: 'Katupila, also known as sweet broomweed, is traditionally used for detoxification and respiratory health. Our instant porridge transforms this powerful herb into a palatable, nourishing meal. Ideal for those seeking natural cleansing and immune support.',
    image: '/products/katupila-porridge.jpg',
    popularity: 72,
    inStock: true,
    nutritionalInfo: { calories: 198, protein: 4.9, carbs: 36.5, fat: 3.4 },
    ingredients: ['Rice Flour', 'Katupila Leaf Powder', 'Coconut Milk Powder', 'Salt'],
    weight: '50g',
    servings: 2,
  },
  {
    id: 6,
    name: 'Iramusu Porridge',
    slug: 'iramusu-porridge',
    category: 'Instant Porridge',
    price: 195,
    description: 'Cooling porridge made from Iramusu (Hemidesmus indicus)',
    fullDescription: 'Iramusu (Indian sarsaparilla) is a renowned blood purifier and cooling agent in Ayurveda. This instant porridge offers a mild, pleasant taste while helping to reduce body heat, improve skin health, and support liver function. A perfect choice for warm climates.',
    image: '/products/iramusu-porridge.jpg',
    popularity: 80,
    inStock: true,
    nutritionalInfo: { calories: 202, protein: 4.6, carbs: 37.2, fat: 3.3 },
    ingredients: ['Rice Flour', 'Iramusu Root Powder', 'Coconut Milk Powder', 'Salt'],
    weight: '50g',
    servings: 2,
  },

  // ========== Herbals Tea Bag ==========
  {
    id: 7,
    name: 'Beli Mal Tea',
    slug: 'beli-mal-tea',
    category: 'Herbals Tea Bag',
    price: 120,
    description: 'Floral tea from Beli flowers (Bael fruit blossom)',
    fullDescription: 'Beli mal (Aegle marmelos flowers) produces a delicately fragrant tea known for its calming and digestive properties. This caffeine-free herbal tea helps relieve constipation, reduces anxiety, and promotes restful sleep. Enjoy hot or iced.',
    image: '/products/beli-mal-tea.jpg',
    popularity: 86,
    inStock: true,
    isPopular: true,
    nutritionalInfo: { calories: 5, protein: 0, carbs: 1, fat: 0 },
    ingredients: ['Dried Beli Flowers'],
    weight: '20g (20 tea bags)',
    servings: 20,
  },
  {
    id: 8,
    name: 'Ranawara Mal Tea',
    slug: 'ranawara-mal-tea',
    category: 'Herbals Tea Bag',
    price: 120,
    description: 'Herbal tea from Ranawara flowers (Cassia auriculata)',
    fullDescription: 'Ranawara is a traditional remedy for diabetes and skin conditions. This mild, golden-hued tea helps regulate blood sugar, purify the blood, and reduce body heat. It has a subtle earthy flavor with natural sweetness.',
    image: '/products/ranawara-mal-tea.jpg',
    popularity: 84,
    inStock: true,
    nutritionalInfo: { calories: 4, protein: 0, carbs: 0.8, fat: 0 },
    ingredients: ['Dried Ranawara Flowers'],
    weight: '20g (20 tea bags)',
    servings: 20,
  },
  {
    id: 9,
    name: 'Nelli & Rasakidha Tea',
    slug: 'nelli-rasakidha-tea',
    category: 'Herbals Tea Bag',
    price: 140,
    description: 'Vitamin C rich blend of Nelli (gooseberry) and Rasakidha',
    fullDescription: 'This unique combination pairs Indian gooseberry (Nelli) with Rasakidha (Tricosanthes cucumerina) for a powerful antioxidant boost. The tea supports immunity, aids digestion, and promotes glowing skin. Tangy and refreshing.',
    image: '/products/nelli-rasakidha-tea.jpg',
    popularity: 90,
    inStock: true,
    isPopular: true,
    nutritionalInfo: { calories: 8, protein: 0.2, carbs: 2, fat: 0 },
    ingredients: ['Dried Nelli Pieces', 'Dried Rasakidha Leaves'],
    weight: '20g (20 tea bags)',
    servings: 20,
  },
  {
    id: 10,
    name: 'Goraka Tea',
    slug: 'goraka-tea',
    category: 'Herbals Tea Bag',
    price: 110,
    description: 'Tangy herbal tea from cured Goraka (Garcinia cambogia)',
    fullDescription: 'Goraka is famous for its weight management and appetite-suppressing properties. This sour, warming tea helps control cravings, supports lipid metabolism, and aids digestion. Perfect after a heavy meal.',
    image: '/products/goraka-tea.jpg',
    popularity: 78,
    inStock: true,
    nutritionalInfo: { calories: 6, protein: 0, carbs: 1.5, fat: 0 },
    ingredients: ['Dried Goraka Rind'],
    weight: '20g (20 tea bags)',
    servings: 20,
  },
  {
    id: 11,
    name: 'Iramusu Tea',
    slug: 'iramusu-tea',
    category: 'Herbals Tea Bag',
    price: 125,
    description: 'Cooling detox tea from Iramusu roots',
    fullDescription: 'Iramusu root tea is a classic blood purifier and body coolant. It helps treat skin conditions like acne and eczema, reduces inflammation, and supports kidney function. Enjoy its mild, pleasant taste daily.',
    image: '/products/ iramusu-tea.jpg',
    popularity: 82,
    inStock: true,
    nutritionalInfo: { calories: 4, protein: 0, carbs: 1, fat: 0 },
    ingredients: ['Dried Iramusu Root Pieces'],
    weight: '20g (20 tea bags)',
    servings: 20,
  },
  {
    id: 12,
    name: 'Polpala Tea',
    slug: 'polpala-tea',
    category: 'Herbals Tea Bag',
    price: 115,
    description: 'Kidney-cleansing herbal tea from Polpala leaves',
    fullDescription: 'Polpala (Aerva lanata) is specifically valued for urinary tract health and kidney stone prevention. This light, earthy tea is a gentle diuretic and helps maintain overall renal function.',
    image: '/products/polpala-tea.jpg',
    popularity: 80,
    inStock: true,
    nutritionalInfo: { calories: 3, protein: 0, carbs: 0.7, fat: 0 },
    ingredients: ['Dried Polpala Leaves'],
    weight: '20g (20 tea bags)',
    servings: 20,
  },
  {
    id: 13,
    name: 'Nilkatarolu Tea',
    slug: 'nilkatarolu-tea',
    category: 'Herbals Tea Bag',
    price: 130,
    description: 'Rare blue-flower tea from Nilkatarolu (Cyanotis axillaris)',
    fullDescription: 'Nilkatarolu is a lesser-known herb used in traditional medicine for wound healing and anti-inflammatory purposes. This rare tea has a subtle, grassy flavor and is rich in bioactive compounds.',
    image: '/products/nilkatarolu-tea.jpg',
    popularity: 65,
    inStock: true,
    nutritionalInfo: { calories: 4, protein: 0.1, carbs: 0.9, fat: 0 },
    ingredients: ['Dried Nilkatarolu Leaves'],
    weight: '20g (20 tea bags)',
    servings: 20,
  },
  {
    id: 14,
    name: 'Pokuru Wadha Tea',
    slug: 'pokuru-wadha-tea',
    category: 'Herbals Tea Bag',
    price: 125,
    description: 'Anti-inflammatory tea from Pokuru Wadha (Clitoria ternatea)',
    fullDescription: 'Also known as butterfly pea flower, Pokuru Wadha produces a stunning blue tea that turns purple with lemon. It is packed with antioxidants, supports brain health, and reduces stress. Naturally caffeine-free.',
    image: '/products/pokuru-wadha-tea.jpg',
    popularity: 88,
    inStock: true,
    isPopular: true,
    nutritionalInfo: { calories: 3, protein: 0, carbs: 0.6, fat: 0 },
    ingredients: ['Dried Pokuru Wadha Flowers'],
    weight: '20g (20 tea bags)',
    servings: 20,
  },
  {
    id: 15,
    name: 'Murunga Tea',
    slug: 'murunga-tea',
    category: 'Herbals Tea Bag',
    price: 135,
    description: 'Nutrient-dense tea from Moringa (Murunga) leaves',
    fullDescription: 'Murunga (Moringa oleifera) is a superfood loaded with vitamins A, C, and E, calcium, and iron. This green, slightly earthy tea boosts energy, supports immunity, and helps combat malnutrition.',
    image: '/products/murunga-tea.jpg',
    popularity: 94,
    inStock: true,
    isPopular: true,
    nutritionalInfo: { calories: 10, protein: 0.8, carbs: 1.5, fat: 0.2 },
    ingredients: ['Dried Murunga Leaves'],
    weight: '20g (20 tea bags)',
    servings: 20,
  },
  {
    id: 16,
    name: 'Veniwelgeta Tea',
    slug: 'veniwelgeta-tea',
    category: 'Herbals Tea Bag',
    price: 140,
    description: 'Blood sugar regulating tea from Veniwelgeta (Coscinium fenestratum)',
    fullDescription: 'Veniwelgeta, also known as yellow vine or Daruharidra, is a potent bitter herb used in Ayurveda for diabetes and metabolic disorders. This tea is very bitter but highly effective for blood sugar control and liver health.',
    image: '/products/veniwelgeta-tea.jpg',
    popularity: 70,
    inStock: true,
    nutritionalInfo: { calories: 5, protein: 0, carbs: 1.2, fat: 0 },
    ingredients: ['Dried Veniwelgeta Stem Pieces'],
    weight: '20g (20 tea bags)',
    servings: 20,
  },
  {
    id: 17,
    name: 'Kidaram Ala Powder',
    slug: 'kidaram-ala-powder',
    category: 'Herbals Tea Bag',
    price: 160,
    description: 'Pure Kidaram Ala (Asparagus racemosus) root powder',
    fullDescription: 'Kidaram Ala, known as Shatavari in Ayurveda, is a renowned female reproductive tonic. This fine powder can be mixed with warm milk or water to support hormonal balance, lactation, and overall vitality.',
    image: '/products/kidaram-ala-powder.jpg',
    popularity: 85,
    inStock: true,
    nutritionalInfo: { calories: 45, protein: 2, carbs: 8, fat: 0.5 },
    ingredients: ['100% Kidaram Ala Root Powder'],
    weight: '100g',
    servings: 20,
    storageInstructions: 'Store in a cool, dry place away from sunlight.',
  },
  {
    id: 18,
    name: 'Rajala Powder',
    slug: 'rajala-powder',
    category: 'Herbals Tea Bag',
    price: 155,
    description: 'Traditional wellness powder from Rajala (Cassia fistula)',
    fullDescription: 'Rajala (golden shower tree) pulp and bark powder is used as a mild laxative and skin health promoter. This powder helps relieve constipation, purify the blood, and treat skin rashes. Mix with honey or warm water.',
    image: '/products/rajala-powder.jpg',
    popularity: 68,
    inStock: true,
    nutritionalInfo: { calories: 38, protein: 1, carbs: 9, fat: 0.2 },
    ingredients: ['Dried Rajala Pulp & Bark Powder'],
    weight: '100g',
    servings: 20,
  },
  {
    id: 19,
    name: 'Bathala Powder',
    slug: 'bathala-powder',
    category: 'Herbals Tea Bag',
    price: 150,
    description: 'Healing powder from Bathala (Sida cordifolia)',
    fullDescription: 'Bathala is an Ayurvedic herb used for nervous system disorders and joint pain. This fine powder can be taken with warm water or ghee to support nerve health, reduce inflammation, and boost energy.',
    image: '/products/bathala-powder.jpg',
    popularity: 72,
    inStock: true,
    nutritionalInfo: { calories: 40, protein: 1.5, carbs: 7.5, fat: 0.3 },
    ingredients: ['Dried Bathala Root & Leaf Powder'],
    weight: '100g',
    servings: 20,
  },

  // ========== Fruits Powder & Chips ==========
  {
    id: 20,
    name: 'Tamarind Powder',
    slug: 'tamarind-powder',
    category: 'Fruits Powder & Chips',
    price: 180,
    description: 'Sour and tangy pure tamarind powder',
    fullDescription: 'Made from sun-dried, de-seeded tamarind pulp, this fine powder is a convenient alternative to fresh or block tamarind. Use it to add authentic sourness to curries, chutneys, and drinks. Rich in magnesium and vitamin C.',
    image: '/products/tamarind-powder.jpg',
    popularity: 88,
    inStock: true,
    nutritionalInfo: { calories: 48, protein: 0.7, carbs: 12, fat: 0.1, calcium: 20 },
    ingredients: ['100% Dried Tamarind Pulp'],
    weight: '100g',
    servings: 25,
  },
  {
    id: 21,
    name: 'Beli Powder',
    slug: 'beli-powder',
    category: 'Fruits Powder & Chips',
    price: 190,
    description: 'Dried Bael fruit powder for digestive health',
    fullDescription: 'Beli (Aegle marmelos) fruit is a traditional remedy for diarrhea, dysentery, and constipation. This powder retains the fruit\'s astringent and aromatic properties. Mix with water or yogurt for a soothing digestive tonic.',
    image: '/products/beli-powder.jpg',
    popularity: 82,
    inStock: true,
    nutritionalInfo: { calories: 52, protein: 1, carbs: 13, fat: 0.2, calcium: 85 },
    ingredients: ['Dried Beli Fruit Pulp'],
    weight: '100g',
    servings: 20,
  },
  {
    id: 22,
    name: 'Wood Apple Powder',
    slug: 'wood-apple-powder',
    category: 'Fruits Powder & Chips',
    price: 200,
    description: 'Tangy-sweet powder from fermented wood apple',
    fullDescription: 'Wood apple (Limonia acidissima) is prized for its unique sour-sweet flavor and medicinal properties. This powder makes an instant refreshing drink when mixed with water and sugar. Excellent for digestion and cooling the body.',
    image: '/products/wood-apple-powder.jpg',
    popularity: 91,
    inStock: true,
    isPopular: true,
    nutritionalInfo: { calories: 55, protein: 0.8, carbs: 14, fat: 0.3, calcium: 90 },
    ingredients: ['Dried Wood Apple Pulp', 'Natural Preservatives'],
    weight: '100g',
    servings: 15,
  },
  {
    id: 23,
    name: 'Nelli Powder',
    slug: 'nelli-powder',
    category: 'Fruits Powder & Chips',
    price: 210,
    description: 'Pure gooseberry (Nelli) powder – vitamin C powerhouse',
    fullDescription: 'Indian gooseberry (Phyllanthus emblica) contains one of the highest concentrations of vitamin C. This sour, astringent powder boosts immunity, promotes hair growth, and improves skin health. Add to smoothies, water, or hair masks.',
    image: '/products/nelli-powder.jpg',
    popularity: 95,
    inStock: true,
    isPopular: true,
    nutritionalInfo: { calories: 44, protein: 0.9, carbs: 10, fat: 0.1, calcium: 25 },
    ingredients: ['Dried Nelli (Gooseberry)'],
    weight: '100g',
    servings: 25,
  },
  {
    id: 24,
    name: 'Waraka Chips',
    slug: 'waraka-chips',
    category: 'Fruits Powder & Chips',
    price: 150,
    description: 'Crunchy chips from Waraka (breadfruit)',
    fullDescription: 'Thinly sliced and kettle-cooked, these Waraka chips are a healthier alternative to potato chips. Breadfruit is rich in complex carbohydrates, fiber, and potassium. Enjoy them plain or with a sprinkle of chili salt.',
    image: '/products/waraka-chips.jpg',
    popularity: 86,
    inStock: true,
    nutritionalInfo: { calories: 480, protein: 3, carbs: 62, fat: 24, calcium: 15 },
    ingredients: ['Fresh Breadfruit', 'Coconut Oil', 'Salt'],
    weight: '100g',
    servings: 2,
  },
  {
    id: 25,
    name: 'Kamaranga Chips',
    slug: 'kamaranga-chips',
    category: 'Fruits Powder & Chips',
    price: 160,
    description: 'Tangy-sweet chips from Kamaranga (star fruit)',
    fullDescription: 'Kamaranga (Averrhoa carambola) is transformed into delightful sweet-and-sour chips. These crispy, translucent chips retain the star fruit\'s unique shape and are lightly dusted with sugar and chili. A tropical snack sensation.',
    image: '/products/kamaranga-chips.jpg',
    popularity: 89,
    inStock: true,
    nutritionalInfo: { calories: 380, protein: 1, carbs: 58, fat: 15, calcium: 5 },
    ingredients: ['Fresh Kamaranga (Star Fruit)', 'Sugar', 'Coconut Oil', 'Chili Flakes'],
    weight: '80g',
    servings: 2,
  },

  // ========== Instant Curry ==========
  {
    id: 26,
    name: 'Kiri Kos Instant Curry',
    slug: 'kiri-kos-instant-curry',
    category: 'Instant Curry',
    price: 250,
    description: 'Creamy jackfruit curry (Kiri Kos) ready in minutes',
    fullDescription: 'Kiri Kos (young jackfruit) is simmered in rich coconut milk with aromatic spices to create this authentic Sri Lankan curry. Just heat and serve with rice or bread. Vegan and gluten-free.',
    image: '/products/kiri-kos-curry.jpg',
    popularity: 92,
    inStock: true,
    isPopular: true,
    nutritionalInfo: { calories: 210, protein: 3.5, carbs: 18, fat: 14, calcium: 40 },
    ingredients: ['Young Jackfruit', 'Coconut Milk', 'Onion', 'Spices (Cumin, Coriander, Turmeric)', 'Salt'],
    weight: '200g',
    servings: 2,
  },
  {
    id: 27,
    name: 'Alu Kasel Instant Curry',
    slug: 'alu-kasel-instant-curry',
    category: 'Instant Curry',
    price: 240,
    description: 'Spiced potato and lentil curry (Alu Kasel)',
    fullDescription: 'Alu Kasel is a hearty blend of potatoes and red lentils in a fragrant, mildly spiced gravy. This instant version captures the homestyle taste of Sri Lankan village cooking. Perfect for a quick vegetarian meal.',
    image: '/products/alu-kasel-curry.jpg',
    popularity: 84,
    inStock: true,
    nutritionalInfo: { calories: 195, protein: 6, carbs: 22, fat: 9, calcium: 30 },
    ingredients: ['Potato', 'Red Lentils', 'Coconut Milk', 'Spices', 'Salt'],
    weight: '200g',
    servings: 2,
  },
  {
    id: 28,
    name: 'Karavila Bedhuma Instant Curry',
    slug: 'karavila-bedhuma-curry',
    category: 'Instant Curry',
    price: 260,
    description: 'Traditional bitter gourd curry (Karavila Bedhuma)',
    fullDescription: 'Karavila (bitter gourd) is prepared in the classic Bedhuma style – sautéed with spices and coconut to reduce bitterness while preserving its blood sugar-regulating properties. A must-try for diabetic-friendly meals.',
    image: '/products/karavila-bedhuma.jpg',
    popularity: 78,
    inStock: true,
    nutritionalInfo: { calories: 175, protein: 4, carbs: 15, fat: 11, calcium: 35 },
    ingredients: ['Bitter Gourd', 'Coconut', 'Onion', 'Spices (Turmeric, Mustard Seeds)', 'Salt'],
    weight: '200g',
    servings: 2,
  },
  {
    id: 29,
    name: 'Polos Ambula Instant Curry',
    slug: 'polos-ambula-curry',
    category: 'Instant Curry',
    price: 270,
    description: 'Sour jackfruit curry (Polos Ambula) with goraka',
    fullDescription: 'Polos Ambula features young jackfruit cooked with goraka (Garcinia cambogia) for a characteristic sour note. This tangy, spicy curry is a beloved Sri Lankan classic that pairs wonderfully with rice and string hoppers.',
    image: '/products/polos-ambula.jpg',
    popularity: 88,
    inStock: true,
    nutritionalInfo: { calories: 205, protein: 3, carbs: 20, fat: 13, calcium: 38 },
    ingredients: ['Young Jackfruit', 'Coconut Milk', 'Goraka', 'Spices', 'Salt'],
    weight: '200g',
    servings: 2,
  },

  // ========== Pepo ==========
  {
    id: 30,
    name: 'Pepo Sesame Cookies',
    slug: 'pepo-sesame-cookies',
    category: 'Pepo',
    price: 180,
    description: 'Crunchy cookies packed with black and white sesame',
    fullDescription: 'These wholesome cookies combine roasted sesame seeds with whole wheat flour and jaggery for a nutty, slightly sweet treat. Rich in calcium and healthy fats. Perfect with tea or coffee.',
    image: '/products/pepo-sesame-cookies.jpg',
    popularity: 87,
    inStock: true,
    nutritionalInfo: { calories: 450, protein: 8, carbs: 52, fat: 24, calcium: 200 },
    ingredients: ['Whole Wheat Flour', 'Sesame Seeds', 'Jaggery', 'Coconut Oil', 'Baking Soda'],
    weight: '150g',
    servings: 6,
  },
  {
    id: 31,
    name: 'Pepo Kids Cookies',
    slug: 'pepo-kids-cookies',
    category: 'Pepo',
    price: 160,
    description: 'Fun, nutritious cookies for children',
    fullDescription: 'Specially formulated for growing kids, these cookies are lower in sugar and enriched with iron and vitamin B. Shaped like animals and lightly sweetened with honey, they make snack time both fun and healthy.',
    image: '/products/pepo-kids-cookies.jpg',
    popularity: 92,
    inStock: true,
    isPopular: true,
    nutritionalInfo: { calories: 410, protein: 6, carbs: 60, fat: 16, calcium: 80 },
    ingredients: ['Whole Wheat Flour', 'Honey', 'Butter', 'Milk Powder', 'Iron Fortification'],
    weight: '150g',
    servings: 6,
  },
  {
    id: 32,
    name: 'Pepo Ginger Cookies',
    slug: 'pepo-ginger-cookies',
    category: 'Pepo',
    price: 185,
    description: 'Spicy ginger cookies with a pleasant kick',
    fullDescription: 'Bold ginger flavor meets buttery crunch in these aromatic cookies. Made with fresh ginger root and a hint of cinnamon, they aid digestion and warm you up on a cold day. A grown-up favorite.',
    image: '/products/pepo-ginger-cookies.jpg',
    popularity: 85,
    inStock: true,
    nutritionalInfo: { calories: 440, protein: 6, carbs: 54, fat: 23 },
    ingredients: ['Wheat Flour', 'Fresh Ginger', 'Butter', 'Brown Sugar', 'Cinnamon'],
    weight: '150g',
    servings: 6,
  },
  {
    id: 33,
    name: 'Pepo Peanuts Cookies',
    slug: 'pepo-peanuts-cookies',
    category: 'Pepo',
    price: 175,
    description: 'Protein-rich cookies with roasted peanut chunks',
    fullDescription: 'Crunchy peanut bits embedded in a melt-in-your-mouth cookie base. These savory-sweet cookies are high in protein and healthy monounsaturated fats. Excellent for an energy boost.',
    image: '/products/pepo-peanuts-cookies.jpg',
    popularity: 88,
    inStock: true,
    nutritionalInfo: { calories: 490, protein: 12, carbs: 45, fat: 30, calcium: 45 },
    ingredients: ['Wheat Flour', 'Roasted Peanuts', 'Butter', 'Jaggery', 'Salt'],
    weight: '150g',
    servings: 6,
  },
  {
    id: 34,
    name: 'Pepo Pumpkin Soup Mix',
    slug: 'pepo-pumpkin-soup-mix',
    category: 'Pepo',
    price: 250,
    description: 'Instant creamy pumpkin soup mix',
    fullDescription: 'Just add hot water to create a velvety, golden pumpkin soup. Made with real dried pumpkin, coconut milk powder, and warming spices like nutmeg. A comforting bowl of goodness in minutes.',
    image: '/products/pepo-pumpkin-soup.jpg',
    popularity: 90,
    inStock: true,
    isPopular: true,
    nutritionalInfo: { calories: 120, protein: 2, carbs: 18, fat: 5, calcium: 20 },
    ingredients: ['Dried Pumpkin Powder', 'Coconut Milk Powder', 'Corn Starch', 'Spices', 'Salt'],
    weight: '120g (makes 4 servings)',
    servings: 4,
  },
  {
    id: 35,
    name: 'Pepo Nutri Mix',
    slug: 'pepo-nutri-mix',
    category: 'Pepo',
    price: 220,
    description: 'Multigrain breakfast mix with nuts and seeds',
    fullDescription: 'A powerhouse blend of roasted multigrains (finger millet, corn, rice), almonds, pumpkin seeds, and dates. Simply mix with hot milk or water for a filling, nutrient-dense breakfast or energy snack.',
    image: '/products/pepo-nutri-mix.jpg',
    popularity: 93,
    inStock: true,
    isPopular: true,
    nutritionalInfo: { calories: 380, protein: 12, carbs: 55, fat: 14, calcium: 110 },
    ingredients: ['Finger Millet', 'Corn', 'Rice', 'Almonds', 'Pumpkin Seeds', 'Dates', 'Cinnamon'],
    weight: '200g',
    servings: 8,
  },
];

// Helper function to get product by slug
export function getProductBySlug(slug: string): Product | undefined {
  return products.find(product => product.slug === slug);
}

// Helper function to get related products (same category, excluding current)
export function getRelatedProducts(product: Product, limit: number = 4): Product[] {
  return products
    .filter(p => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}